services:
  # MongoDB Database
  mongodb:
    image: mongo:7-jammy
    container_name: expense-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: expense_management_dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - expense-dev-network

  # Backend API (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: expense-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URL: mongodb://admin:admin123@mongodb:27017/expense_management_dev?authSource=admin
      JWT_SECRET: dev-jwt-secret-key
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_dev_uploads:/app/uploads
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - expense-dev-network
    command: npm run dev

  # Frontend (Development với hot reload)
  frontend:
    build:
      context: ./frontend-vite
      dockerfile: Dockerfile.dev
    container_name: expense-frontend-dev
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:5000
    volumes:
      - ./frontend-vite:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - expense-dev-network

volumes:
  mongodb_dev_data:
    driver: local
  backend_dev_uploads:
    driver: local

networks:
  expense-dev-network:
    driver: bridge
